name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY: "django-webapp-code"
  CONTAINER_NAME: "django-webapp"
  ELASTIC_BEANSTALK_APP_NAME: "django-webapp-eb"
  ELASTIC_BEANSTALK_ENV_NAME: "team99"
  ELASTIC_BEANSTALK_APP_VERSION: "app-250323_170124889142"

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to AWS ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and push it to ECR so that it can be deployed to Elastic Beanstalk.
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: AWS Elastic Beanstalk environment
      id: eb-env
      run: |
        # Deploy
        cd eb
        cat Dockerrun.aws.json | sed "s/<AWS_ACCOUNT_ID>/${{secrets.AWS_ACCOUNT_ID}}/"  | sed "s/<ECR_REPOSITORY>/${{ECR_REPOSITORY}}/" > Dockerrun.aws.json
        zip -r ../${{github.run_id}}.zip Dockerrun.aws.json
        aws s3 cp "../${{github.run_id}}.zip" s3://elasticbeanstalk-us-east-1-${{ secrets.AWS_ACCOUNT_ID }}/django-webapp-eb/
        aws elasticbeanstalk create-application-version --application-name $ELASTIC_BEANSTALK_APP_NAME --version-label ${{github.run_id}} --description ${{github.run_id}} --source-bundle S3Bucket="elasticbeanstalk-us-east-1-${{ secrets.AWS_ACCOUNT_ID }}",S3Key="django-webapp-eb/${{github.run_id}}.zip"
        aws elasticbeanstalk update-environment --application-name $ELASTIC_BEANSTALK_APP_NAME --environment-name $ELASTIC_BEANSTALK_ENV_NAME --version-label ${{github.run_id}}
        aws elasticbeanstalk wait environment-updated --application-name $ELASTIC_BEANSTALK_APP_NAME --environment-name $ELASTIC_BEANSTALK_ENV_NAME