name: Change JSON

on:
  push:

env:
  ACTIONS_RUNNER_DEBUG: true

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: "show dir"
        id: show-dir
        run: |
          pwd
          ls -lR
        

      - name: "Read JSON"
        uses: actions/github-script@v7
        id: check-env
        with:
            result-encoding: string
            script: |
              const fs = require('fs'); // Import the fs (File System) module

              // Define the path to the file
              console.log('Current working directory:', process.cwd());
              const filePath = '.housekeeping/elasticbeanstalk/Dockerrun.aws.json';

              // Read the file and parse it
              fs.readFile(filePath, 'utf8', (err, data) => {
                if (err) {
                  console.error('Error reading the file:', err);
                  return;
                }

                try {
                  // Parse the JSON data
                  const jsonData = JSON.parse(data);
                  console.log('Parsed JSON data:', jsonData);
                } catch (parseErr) {
                  console.error('Error parsing the JSON:', parseErr);
                }
              });
