name: Change JSON

on:
  push:

env:
  ACTIONS_RUNNER_DEBUG: true

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Dockerrun
        uses: actions/github-script@v7
        id: check-env
        with:
            result-encoding: string
            script: |
              try {
                const fs = require('fs')
                const jsonString = fs.readFileSync('.housekeeping/elasticbeanstalk/Dockerrun.aws.json')
                var apps = JSON.parse(jsonString)
                console.log('Parsed JSON data:', apps)
                apps["Image"]["Name"] = 'Mierda con tomate'
                console.log('Parsed JSON data:', apps);
                fs.writeFileSync('.housekeeping/elasticbeanstalk/Dockerrun.aws.json',JSON.stringify(apps))
              } catch(err) {
                core.error("Error while reading or parsing the JSON")
                core.setFailed(err)
              }
              
